### ISSUE TITLE
Issue running rector on the src files

### ISSUE THREAD

**Issue by SvenBuis** [cakephp/upgrade#164]
Hello,

When running `bin/cake upgrade rector --rules cakephp40 /var/www/html/` I get the following error:

`PHP Fatal error: During class fetch: Uncaught PHPStan\Broker\ClassAutoloadingException: Class Cake\ORM\Locator\LocatorAwareTrait not found.`

**Comment by robertpustulka** [comment]
@SvenBuis try locking rector to version 0.9.*: `composer require rector/rector:~0.9.0 -W`

I suspect the tool is incompatible with rector 0.10?

**Comment by othercorey** [comment]
You shouldn't be running the ruleset on the base directory. It should be on the src/, config/, tests/ directories.  See the readme for an example.

**Comment by robertpustulka** [comment]
I had the same issue and #165 fixed it for me.

**Comment by lgraham1** [comment]
I had the same problem as the OP, but strangely `composer require rector/rector:~0.9.0 -W` *did not* fix it for me. With rector ~0.9.0 `bin/cake upgrade rector --verbose ~/projects/myproject/src` (same thing with tests and config) seemed to hang indefinitely after:
```
Detecting autoload file for /Users/l.graham/projects/myproject/src
-> Checking /Users/l.graham/projects/myproject/src/vendor/autoload.php
-> Checking /Users/l.graham/projects/myproject/vendor/autoload.php
-> Found /Users/l.graham/projects/myproject/vendor/autoload.php
Running /Users/l.graham/tools/upgrade/vendor/bin/rector process  --autoload-file='/Users/l.graham/projects/myproject/vendor/autoload.php' --config='/Users/l.graham/tools/upgrade/config/rector/cakephp40.php' --working-dir='/Users/l.graham/projects/myproject/src' '/Users/l.graham/projects/myproject/src'
```

I also tried various other versions of rector and on two other Cake 3.x projects, but I would either get errors or the upgrade tool would hang. What _did_ work for me was installing the full framework into the upgrade tool with `composer require cakephp/cakephp`. I see there is a mention in the README of how having the framework in the upgrade tool can cause problems, but in this case it seems to have fixed my problem. 

There were some things it missed (e.g. `MyTable::defaultConnectionName() must be compatible with Cake\ORM\Table::defaultConnectionName(): string`, `MyForm::_execute(array $data) must be compatible with Cake\Form\Form::_execute(array $data): bool` and `AppController::initialize() must be compatible with Cake\Controller\Controller::initialize(): void`), but I'm not sure if that was due to my workaround, the app I was upgrading, or the tool itself. In any case they can be found easily enough with phpstan or tests. Thank you for creating this tool, it saved me a lot of time and effort. 

In case it's relevant, this was with zsh 5.8 on macOS 11.2.3 build 20D91 with PHP 7.4.16. The target application was on CakePHP 3.9.8. After installing the upgrade tool and and cakephp into the upgrade tool I have rector 0.10.6, rector-cakephp 0.10.3 and cakephp 4.2.5.
