### ISSUE TITLE
Update 4.0 to 4.1 Fatal error

### ISSUE THREAD

**Issue by brunof20** [cakephp/upgrade#173]
Hello

When run `bin/cake upgrade rector --rules cakephp41 <my-app/src>`

 I get the following error:

> 0/876 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%Fatal error: Class PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTextNode contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (PHPStan\PhpDocParser\Ast\Node::setAttribute, PHPStan\PhpDocParser\Ast\Node::hasAttribute, PHPStan\PhpDocParser\Ast\Node::getAttribute) in /var/www/my-app/vendor/phpstan/phpdoc-parser/src/Ast/PhpDoc/PhpDocTextNode.php on line 5

**Comment by othercorey** [comment]
Can you show which version of rectorphp/rector was installed?

**Comment by brunof20** [comment]
Yes,
`"rector/rector": "~0.10.20"`

I have checkout of branch 'master'

**Comment by othercorey** [comment]
@markstory

**Comment by markstory** [comment]
What version of PHP are you using?

**Comment by brunof20** [comment]
PHP Version 7.4

**Comment by markstory** [comment]
I was able to reproduce this locally.

This looks like it is caused by a conflicting version between your application's dependencies and the upgrade tool. Unfortunately because of how rector works it needs to use your applications' autoloader in addition to the upgrade tool's autoloader.

You should be able to resolve this by removing the `vendor/phpstan` directory in your application's vendor directory. This should let you run rector with more success.

**Comment by brunof20** [comment]
OKey, It worked. Thanks!
