### ISSUE TITLE
[5.x] AbstractRector not found

### ISSUE THREAD

**Issue by Rakasch** [cakephp/upgrade#275]
What i did:
`git checkout 5.x`
`git pull`
`composer install --no-dev`
`bin/cake upgrade rector --rules cakephp50 /var/www/html/myproject`

I get the following error:
[ERROR] Class "Rector\Rector\AbstractRector" not found 

I checked my vendor files. The file exists. See Screenshot.

It does state "Reactor applied successfully". But I have some doubts because of the error.

Comment:
I've already used the upgrade tool for the 4.x branch. The 4.x branch works fine, so I assume there is a problem with the 5.x branch.

![image](https://github.com/cakephp/upgrade/assets/8471027/cfed16dd-cb1d-446d-9d1e-2ce12b7e496b)

**Comment by othercorey** [comment]
If you pulled the upgrade repo recently, this is probably from the rector 1/0 upgrade. I didn't notice any errors, but if it's still passing when throwing this error, that would explain it.

**Comment by garas** [comment]
`AbstractRector` in your screenshot is in `Rector\Core\Rector` namespace, which was renamed to `Rector\Rector` in Rector 0.19.

When you switched branch to 5.x, `composer.json` was checked out, but `composer.lock` was untouched because it is not in Git.

`composer install` used  `.lock` file and stayed with 4.x dependencies. You got warning because `.lock` doesn't match `.json` dependencies.

Use `composer update  --no-dev` to update to 5.x dependencies.

**Comment by Rakasch** [comment]
@garas Thanks, that's one of those moments when you (me) feel really stupid for overlooking it.
